DROP TABLE IF EXISTS BOOK;  
CREATE TABLE BOOK (  
BOOK_ID VARCHAR(8)  PRIMARY KEY,  
BOOK_NAME VARCHAR(50) NOT NULL,  
AUTHOR VARCHAR(50) NOT NULL,
AVAILABLE_COPIES INT(8) NOT NULL,
TOTAL_COPIES INT(8) NOT NULL   
);